# Generated by Django 5.1.3 on 2024-11-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_post_id_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_facebook',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_up',
            field=models.TextField(null=True),
        ),
    ]
