# Generated by Django 5.1.3 on 2024-11-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_link_facebook_post_link_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(db_comment='1: User lấy dữ liệu, 2: User đăng bài', default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='type_page',
            field=models.IntegerField(db_comment='1: Page lấy dữ liệu, 2: Page đăng bài', default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='up',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_comment='1: Chưa thực thi, 2: Đã thực thi', default=1, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.page')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.post')),
            ],
        ),
    ]
