# Generated by Django 5.1.3 on 2024-11-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_code_user_type_alter_page_type_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pid',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='up',
            field=models.IntegerField(db_comment='0: Chờ duyệt, 1: Đã duyệt, 2: Đã huỷ', default=0),
        ),
    ]
