# Generated by Django 5.1.3 on 2024-11-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_pid_alter_post_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='follow_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
